
sudo: required
dist: trusty

language: python
python:
  - 3.4

install:
  # install java (needed by html validator)
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle

  # install ruby
  - rvm install 2.2
  - ruby -v

  # node.js deps
  - npm install -g jasmine-node
  - npm install

  # set up the server for testing
  - ./server_setup.sh

before_script:
  - ./run_server.sh --config tests/config.test.json &
  # The server needs a little time to ensure it has generated some data
  # before we start testing the API.
  - sleep 5

script:
  # server tests
  - jasmine-node tests/

  # webapp tests
  # run each individually so it doesn't stop on the first error
  - grunt htmllint
  - grunt jshint
  - grunt csslint
  - grunt bootlint
